obj_env_cfg:
  joint_type: prismatic
  data_path: dataset/one_drawer_cabinet/45162_link_1
  obj_index: 45162
  joint_index: 1
  obj_description: cabinet
  active_link_name: link_1
  active_joint_name: joint_1
  load_joint_state: 0
  load_pose:
  - 0.881328821182251
  - 0.029884938150644302
  - 0.6381257772445679
  load_quat:
  - 0.9994285106658936
  - 0.013371272012591362
  - -0.0004153406189288944
  - -0.031044410541653633
  load_scale: 0.920194231213939
task_cfg:
  instruction: open the cabinet
  task_id: 19
manip_env_cfg:
  tasks:
    '0_1':
      manip_start_state: 0.09541173390703885
      manip_end_state: 0.19541173390703886
    '0_2':
      manip_start_state: 0.002911458411100232
      manip_end_state: 0.20291145841110025
    '0_3':
      manip_start_state: 0.07224168692076102
      manip_end_state: 0.3722416869207611
    '1_0':
      manip_start_state: 0.15059604812449223
      manip_end_state: 0.05059604812449223
    '1_2':
      manip_start_state: 0.16798530077379586
      manip_end_state: 0.2679853007737959
    '1_3':
      manip_start_state: 0.10367116879695001
      manip_end_state: 0.30367116879695
    '2_0':
      manip_start_state: 0.21556747572208693
      manip_end_state: 0.015567475722086915
    '2_1':
      manip_start_state: 0.21384464255528204
      manip_end_state: 0.11384464255528204
    '2_3':
      manip_start_state: 0.20458779002051666
      manip_end_state: 0.30458779002051667
    '3_0':
      manip_start_state: 0.39267760911046934
      manip_end_state: 0.0926776091104693
    '3_1':
      manip_start_state: 0.31581743513373023
      manip_end_state: 0.11581743513373022
    '3_2':
      manip_start_state: 0.3234793918162397
      manip_end_state: 0.2234793918162397
