obj_env_cfg:
  joint_type: prismatic
  data_path: dataset/one_drawer_cabinet/45243_link_1
  obj_index: 45243
  joint_index: 1
  obj_description: cabinet
  active_link_name: link_1
  active_joint_name: joint_1
  load_joint_state: 0
  load_pose:
  - 0.9920141100883484
  - 0.19149252772331238
  - 0.6611735224723816
  load_quat:
  - 0.997190535068512
  - -0.007884086109697819
  - -0.00058892578817904
  - 0.07448818534612656
  load_scale: 1.0183202149392154
task_cfg:
  instruction: open the cabinet
  task_id: 46
manip_env_cfg:
  tasks:
    '0_1':
      manip_start_state: 0.037956115025009445
      manip_end_state: 0.13795611502500946
    '0_2':
      manip_start_state: 0.08326594633169448
      manip_end_state: 0.2832659463316945
    '0_3':
      manip_start_state: 0.029193522712738076
      manip_end_state: 0.3291935227127381
    '1_0':
      manip_start_state: 0.181490331438806
      manip_end_state: 0.08149033143880599
    '1_2':
      manip_start_state: 0.12966630687345704
      manip_end_state: 0.22966630687345704
    '1_3':
      manip_start_state: 0.1381339838705542
      manip_end_state: 0.3381339838705542
    '2_0':
      manip_start_state: 0.20428992674934904
      manip_end_state: 0.004289926749349027
    '2_1':
      manip_start_state: 0.29027213568290355
      manip_end_state: 0.19027213568290355
    '2_3':
      manip_start_state: 0.23746016599751518
      manip_end_state: 0.33746016599751516
    '3_0':
      manip_start_state: 0.3988997180309617
      manip_end_state: 0.09889971803096165
    '3_1':
      manip_start_state: 0.3645086473097379
      manip_end_state: 0.1645086473097379
    '3_2':
      manip_start_state: 0.3829346568307788
      manip_end_state: 0.2829346568307788
