obj_env_cfg:
  joint_type: prismatic
  data_path: dataset/one_drawer_cabinet/45243_link_3
  obj_index: 45243
  joint_index: 3
  obj_description: cabinet
  active_link_name: link_3
  active_joint_name: joint_3
  load_joint_state: 0
  load_pose:
  - 0.8370588421821594
  - 0.13848313689231873
  - 0.6979329586029053
  load_quat:
  - 0.9996883273124695
  - 0.0060475361533463
  - 0.00014651214587502182
  - 0.024219200015068054
  load_scale: 0.9922764447177709
task_cfg:
  instruction: open the cabinet
  task_id: 50
manip_env_cfg:
  tasks:
    '0_1':
      manip_start_state: 0.07758875610611707
      manip_end_state: 0.17758875610611707
    '0_2':
      manip_start_state: 0.09425850139726044
      manip_end_state: 0.29425850139726045
    '0_3':
      manip_start_state: 0.02664405701286834
      manip_end_state: 0.32664405701286836
    '1_0':
      manip_start_state: 0.16987470998352933
      manip_end_state: 0.06987470998352932
    '1_2':
      manip_start_state: 0.19220843208082478
      manip_end_state: 0.2922084320808248
    '1_3':
      manip_start_state: 0.1719083338643158
      manip_end_state: 0.3719083338643158
    '2_0':
      manip_start_state: 0.2994057725225821
      manip_end_state: 0.09940577252258209
    '2_1':
      manip_start_state: 0.2672004314759169
      manip_end_state: 0.16720043147591687
    '2_3':
      manip_start_state: 0.2891125564065904
      manip_end_state: 0.38911255640659037
    '3_0':
      manip_start_state: 0.39525847361111555
      manip_end_state: 0.0952584736111155
    '3_1':
      manip_start_state: 0.3072922271810754
      manip_end_state: 0.1072922271810754
    '3_2':
      manip_start_state: 0.3520599228468658
      manip_end_state: 0.25205992284686585
