obj_env_cfg:
  joint_type: revolute
  data_path: dataset/one_door_cabinet/45780_link_1
  obj_index: 45780
  joint_index: 1
  obj_description: cabinet
  active_link_name: link_1
  active_joint_name: joint_1
  load_joint_state: 0
  load_pose:
  - 0.8157843947410583
  - 0.1112278401851654
  - 0.513768196105957
  load_quat:
  - 0.9991773366928101
  - 0.02465767413377762
  - 0.0007943389355204999
  - 0.03218817338347435
  load_scale: 0.9005452368861225
task_cfg:
  instruction: open the cabinet
  task_id: 61
manip_env_cfg:
  tasks:
    '0_1':
      manip_start_state: 0.036983866310432906
      manip_end_state: 0.21151679150986585
    '0_2':
      manip_start_state: 0.12716358510544506
      manip_end_state: 0.47622943550431096
    '0_3':
      manip_start_state: 0.0421198327620112
      manip_end_state: 0.5657186083603101
    '1_0':
      manip_start_state: 0.21110674670713866
      manip_end_state: 0.03657382150770572
    '1_2':
      manip_start_state: 0.17975314663079484
      manip_end_state: 0.35428607183022776
    '1_3':
      manip_start_state: 0.1827132940291576
      manip_end_state: 0.5317791444280235
    '2_0':
      manip_start_state: 0.42122524497821495
      manip_end_state: 0.07215939457934904
    '2_1':
      manip_start_state: 0.45228089641705377
      manip_end_state: 0.27774797121762085
    '2_3':
      manip_start_state: 0.3780850394095519
      manip_end_state: 0.5526179646089848
    '3_0':
      manip_start_state: 0.6512639688699993
      manip_end_state: 0.12766519327170037
    '3_1':
      manip_start_state: 0.6708242718212462
      manip_end_state: 0.32175842142238026
    '3_2':
      manip_start_state: 0.6126046016277774
      manip_end_state: 0.4380716764283444
